#!/bin/bash

ENVMT=everbrite-customer-portal
URL=everbrite-customer-portal.pantheonsite.io

function _cim {
  set -x
  drush @$ENVMT.$1 cim -y sync
  _cr $1
  set +x
}

function _cr {
  set -x
  terminus env:cc $ENVMT.$1
  set +x
}

function _open {
  set -x
  open http://$1-$URL
  set +x
}

function _sleep {
  echo -n sleeping $1 seconds:' '
  a=$1
  while [ $a -gt 0 ]; do
    echo -n .
    sleep 1
    a=$[ $a - 1 ]
  done
  echo \ ok
}

function _tag {
  set -x
  CUR_TAG=$(git tag | grep -i pantheon_$1 | cut -d _ -f 3 | sort -nr | head -n 1)
  let NEXT_TAG=$CUR_TAG+1
  git tag pantheon_$1_$NEXT_TAG
  git push --tags
  set +x
}

function _updb {
  set -x
  echo yes | terminus remote:drush $ENVMT.$1 updb -y
  set +x
}

case "$1" in

  cim)
    _cim $2
    ;;
  cr)
    _cr $2
    ;;
  dev)
    _updb dev
    _cim dev
    _open dev
    ;;
  live)
    _tag live
    _sleep 15
    _updb live
    _cim live
    _open live
    ;;
  open)
    _open $2
    ;;
  sleep)
    _sleep $2
    ;;
  tag)
    _tag $2
    ;;
  test)
    _tag test
    _sleep 15
    _updb test
    _cim test
    _open test
    ;;
  updb)
    _updb $2
    ;;
  *)
    echo `basename $0`: simple utility for pantheon
    cat <<EOF
ENV is dev|test|live
args:
    tag   ENV: tag latest git HEAD for deployment on ENV (not dev)
    cim   ENV: config sync and cache reload on ENV
    cr    ENV: cache reload on ENV
    open  ENV: open browser to ENV
    updb  ENV: perform db updates on ENV

    dev : updb, cim and open DEV
    test: tag, updb, cim, and open TEST
    live: tag, updb, cim, and open LIVE

    sleep NUM: sleep NUM seconds
    help: this help
EOF
    ;;

esac
